### ISSUE TITLE
Pure Python model

### ISSUE THREAD

**Issue by prusnak** [secworks/poly1305#1]
In other repositories I see you use pure Python code for the driving models, but in this repo you have one written in C.

Would you be interested in PR which replaces this with a pure Python implementation of Poly1305?

**Comment by secworks** [comment]
Aloha!
Yes, that could be interesting. 

If the model is clean, easy to follow and can generate loads of intermediate results (can be easily adapted), if the provenance is good (it is clear who is the author, that it is not a copy without proper attributio) and the license is BSD, MIT or Apache2 it would be possible to add.

Does the model exist? If so, can you post a link to it?

**Comment by secworks** [comment]
Forgot to add: I appreciate the offer!

**Comment by secworks** [comment]
@prusnak This issue is two-ish years. Should I close it?

**Comment by prusnak** [comment]
Sorry, I missed your reaction in 2020 and now I have moved to other things. Yes, I am closing this.
